## @section Global
## @param environment Environment name
## @default "flowcore"
environment: flowcore
## @param platform Platform that these microservices are part of
platform: flowcore
## @param imageRepository The image repository to use for all microservices in this chart
imageRepository: 305363105399.dkr.ecr.eu-west-1.amazonaws.com
## @extra oidcWellKnownUrl The OIDC well known URL to use for all microservices in this chart
## @param imagePullSecrets List of image pull secrets to use for all microservices in this chart
imagePullSecrets: []
## @section Domain Settings
## @param transport Ingress settings for the transport domain
transport: {}
  ## @extra transport.<name> Environment variables for the transport in object format



## @section Deployments
## @param deployments [object] List of microservices to deploy
deployments: {}
## @extra deployments.<microservice> Configuration entry for a microservice
#  APIKeyCommands:
## @extra deployments.<microservice>.enabled Whether to deploy this microservice [boolean]
#    enabled: true
## @extra deployments.<microservice>.component What type of microservice this is [api, adapter, ...]
#    component: api
## @extra deployments.<microservice>.restartPolicy The restart policy to use for this microservice, defaults to Always [Always, OnFailure, Never]
#    restartPolicy: Always
## @extra deployments.<microservice>.imagePullSecrets List of image pull secrets to use for this microservice [array]
#    imagePullSecrets: []
## @extra deployments.<microservice>.source What type of source this microservice uses [node, go, rust, ...]
#    source: node
## @extra deployments.<microservice>.deployment Configuration for the deployment
#    deployment:
## @extra deployments.<microservice>.deployment.maxSurge The maximum number of pods that can be scheduled above the desired number of pods [integer]
#      maxSurge: "25%"
## @extra deployments.<microservice>.deployment.maxUnavailable The maximum number of pods that can be unavailable during the update process [integer]
#      maxUnavailable: 0
## @extra deployments.<microservice>.deployment.image The image name to use for this microservice, excluding the repository [string]
#      image: "auth-api-key-commands"
## @extra deployments.<microservice>.deployment.tag The image tag to use for this microservice [string]
#      tag: "latest"
## @extra deployments.<microservice>.deployment.replicas The number of replicas to deploy [integer]
#      replicas: 1
## @extra deployments.<microservice>.deployment.resources Resource configuration for this microservice
#      resources: {}
## @extra deployments.<microservice>.service Service configuration for this microservice if needed
#    service:
## @extra deployments.<microservice>.service.enabled Whether to deploy a service for this microservice [boolean]
#      enabled: true
## @extra deployments.<microservice>.service.httpPort The http port to expose for this microservice [integer]
#      httpPort: 3000
## @extra deployments.<microservice>.service.extraPorts Extra ports to expose for this microservice
#      extraPorts:
## @extra deployments.<microservice>.service.extraPorts.<name> Configuration for an extra port to expose
#        grpc:
## @extra deployments.<microservice>.service.extraPorts.<name>.port The port to expose [integer]
#          port: 5000
## @extra deployments.<microservice>.service.extraPorts.<name>.type The type of port to expose [TCP, UDP, ...]
#          type: TCP
## @extra deployments.<microservice>.ingress List of Ingress configurations for this microservice if needed [array]
#    ingress:
## @extra deployments.<microservice>.ingress.hosts The hosts to use for this microservice, list of strings [array]
#      - hosts:
#          - "auth.flowcore.io"
## @extra deployments.<microservice>.ingress.tlsSecret The tls secret to use for this microservice [string]
#        tlsSecret: "tls-secret"
## @extra deployments.<microservice>.env Environment variables to set for this microservice
#    env:
## @extra deployments.<microservice>.env.<variable> Configuration for an environment variable
#      HELLO:
## @extra deployments.<microservice>.env.<variable>.value The value to set for this environment variable, use valueFrom if you want to use a secret [string]
#        value: World
## @extra deployments.<microservice>.useTransport Array or Object of transport services to use for this microservice
#    useTransports:
## @extra deployments.<microservice>.useTransport.<name> The name of the transport service to use
#      - nats
## @extra deployments.<microservice>.useTransport.<name>.overrides Overrides for the transport service
#      - name: nats
#        overrides:
## @extra deployments.<microservice>.useTransport.<name>.overrides.<variable> Configuration for an environment variable
#          NATS_QUEUE:
## @extra deployments.<microservice>.useTransport.<name>.overrides.<variable>.value The value to set for this environment variable, use valueFrom if you want to use a secret [string]
#            value: user-service
## @extra deployments.<microservice>.useFlowcoreWebhooks Whether to use flowcore webhooks for this microservice [boolean]
## @extra deployments.<microservice>.sidecars list of sidecars to deploy
#    sidecars:
## @extra deployments.<microservice>.sidecars.<name> Configuration for a sidecar
#      sideCarA:
## @extra deployments.<microservice>.sidecars.<name>.enabled Whether to deploy this sidecar [boolean]
## @extra deployments.<microservice>.sidecars.<name>.repo The image repository to use for this sidecar, optional [string]
## @extra deployments.<microservice>.sidecars.<name>.image The image name to use for this sidecar, excluding the repository [string]
## @extra deployments.<microservice>.sidecars.<name>.tag The image tag to use for this sidecar [string]
## @extra deployments.<microservice>.sidecars.<name>.env Environment variables to set for this sidecar
## @extra deployments.<microservice>.sidecars.<name>.env.<variable> Configuration for an environment variable
## @extra deployments.<microservice>.sidecars.<name>.env.<variable>.value The value to set for this environment variable, use valueFrom if you want to use a secret [string]
## @extra deployments.<microservice>.sidecars.<name>.httpPort The http port for this sidecar, used for health checks [integer]
## @extra deployments.<microservice>.sidecars.<name>.resources Resource configuration for this sidecar
## @extra deployments.<microservice>.volumes list of config volumes to deploy
## @extra deployments.<microservice>.volumes.<name> Configuration for a volume
## @extra deployments.<microservice>.volumes.<name>.config Config Map to use for this volume
## @extra deployments.<microservice>.volumes.<name>.secret Secret to use for this volume
## @extra deployments.<microservice>.volumes.<name>.mountPath The mount path to use for this volume
## @extra deployments.<microservice>.volumes.<name>.subPath The sub path to use for this volume, optional
