## @section Controller configuration
## @param controllerImage [default: flowcoreio/secret-request-controller] The image of the secret request controller 
controllerImage: flowcoreio/secret-request-controller
## @param controllerTag [default: 1.0.5] The tag of the secret request controller
controllerTag: "1.0.5"
## @param replicaCount [default: 1] Number of replicas for the secret request controller
replicaCount: 1
## @param resources [object] Resource requests and limits for the secret request controller see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ for more info
resources: 
  ## @param resources.requests [object] Resource requests for the secret request controller
  requests:
    ## @param resources.requests.cpu [default: 65m] The amount of CPU to request for the secret request controller
    cpu: 65m
    ## @param resources.requests.memory [default: 122Mi] The amount of memory to request for the secret request controller
    memory: 122Mi
  ## @param resources.limits [object] Resource limits for the secret request controller
  limits:
    ## @param resources.limits.cpu [default: 120m]The amount of CPU to limit for the secret request controller
    cpu: 120m
    ## @param resources.limits.memory [default: 148Mi] The amount of memory to limit for the secret request controller
    memory: 148Mi
## @param service [object] Configuration for the service
service:
  ## @param service.port [default: 3000] The port the service listens on
  port: 3000
## @extra namespace [string] The namespace to deploy the secret request controller in

## @section Metacontroller
## @param metacontroller-helm [object] see https://metacontroller.github.io/metacontroller/guide/helm-install.html for more configuration options
metacontroller-helm:
## @param metacontroller-helm.enabled [default: true] Enable the metacontroller helm chart
  enabled: true
## @param metacontroller-helm.replicas [default: 2] Number of replicas for the metacontroller deployment
  replicas: 2
## @param metacontroller-helm.commandArgs [array] Command arguments for the metacontroller deployment
  commandArgs:
    - --zap-log-level=4
    - --discovery-interval=20s
    - --leader-election=true
    - --workers=10