{{- range $microservice, $spec := .Values.deployments }}
{{- if $spec.enabled }}
{{- $serviceName := cat $microservice | kebabcase }}
{{- $component := "service" }}
{{- if $spec.component }}
{{ $component = $spec.component }}
{{- end }}
{{- $env := $.Values.environment | default "flowcore" }}
{{- $platform := $.Values.platform | default "flowcore" }}
{{- $source := "node" }}
{{- if $spec.source }}
{{- $source = $spec.source }}
{{- end }}
{{- $repoBase := $.Values.imageRepository -}}
{{- $replicas := $spec.deployment.replicas | default 1 }}
{{- $httpPort := 3000 }}
{{- if $spec.service }}
{{- if $spec.service.httpPort }}
{{- $httpPort = $spec.service.httpPort }}
{{- end }}
{{- end }}
{{- $baseUrl := $.Values.baseUrl | default "flowcore.io" }}
{{- $host := cat ($serviceName | kebabcase) ".api." $baseUrl }}
{{- $tlsSecretName := "api-flowcore-io-wildcard-tls" }}
{{- if $spec.ingress }}
{{- if $spec.ingress.host }}
{{- $host = $spec.ingress.host }}
{{- end }}
{{- if $spec.ingress.tlsSecret }}
{{- $tlsSecretName = $spec.ingress.tlsSecret }}
{{- end }}
{{- end }}
{{- $wellKnownUrl := $.Values.oidcWellKnownUrl }}
{{- $sidecarHealthPort := add $httpPort 1 }}
{{ $maxSurge := "25%" }}
{{ $maxUnavailable := 0 }}
{{- if $spec.deployment }}
{{- $maxSurge = $spec.deployment.maxSurge }}
{{- $maxUnavailable = $spec.deployment.maxUnavailable }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels: &common_labels
    app: {{ $serviceName }}
    app.kubernetes.io/name: {{ $serviceName }}
    app.kubernetes.io/version: {{ $spec.deployment.tag | quote }}
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/part-of: {{ $platform }}
    tags.datadoghq.com/env: {{ $env }}
    tags.datadoghq.com/service: {{ $serviceName }}
    tags.datadoghq.com/version: {{ $spec.deployment.tag | quote }}
spec:
  replicas: {{ $replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ $maxSurge }}
      maxUnavailable: {{ $maxUnavailable }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels: *common_labels
      annotations:
        ad.datadoghq.com/{{ $serviceName }}.logs: '[{"source":"node","service":"{{ $serviceName }}"}]'
        ad.datadoghq.com/{{ $serviceName }}.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:%%port%%/metrics",
                  "namespace": "{{ $platform }}",
                  "metrics": ["*"]
                }
              ]
            }
          }
        {{- range $sidecarName, $sidecarSpec := $spec.sidecars }}
        {{- if $sidecarSpec.enabled }}
        {{- $sidecarSafeName := $sidecarName | kebabcase }}
        ad.datadoghq.com/{{ $sidecarSafeName }}.logs: '[{"source":"node","service":"{{ $sidecarSafeName }}"}]'
        ad.datadoghq.com/{{ $sidecarSafeName }}.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:%%port%%/metrics",
                  "namespace": "{{ $platform }}",
                  "metrics": ["*"]
                }
              ]
            }
          }
        {{- end }}
        {{- end }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ $serviceName }}
          image: "{{ $repoBase }}/{{ $spec.deployment.image }}:{{ $spec.deployment.tag }}"
          env:
            {{- range $index, $transportName := $spec.useTransports }}
            {{- $transportTarget := "" }}
            {{- if eq (kindOf $transportName) "string" }}
            {{- $transportTarget = $transportName }}
            {{- else }}
            {{- $transportTarget = $transportName.name }}
            {{- end }}
            {{- range $transportKey, $transportValue := index $.Values.transport $transportTarget }}
            - name: {{ $transportKey }}
              {{- if eq (kindOf $transportName) "string" }}
              {{- $transportValue | toYaml | nindent 14 }}
              {{- else }}
              {{- if $transportName.overrides }}
              {{- range $overrideKey, $overrideValue := $transportName.overrides }}
              {{- if eq $overrideKey $transportKey }}
              {{- $overrideValue | toYaml | nindent 14 }}
              {{- end }}
              {{- end }}
              {{- end }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- range $envKey, $envValue := $spec.env }}
            - name: {{ $envKey }}
              {{- $envValue | toYaml | nindent 14 }}
            {{- end }}
            - name: OIDC_WELLKNOWN_URL
              value: {{ $wellKnownUrl }}
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_APM_ENABLED
              value: "true"
          {{- if $spec.volumes }}
          volumeMounts:
          {{- range $volumeMountName, $volumeSpec := $spec.volumes }}
            - name: {{ cat $volumeMountName "volume"| kebabcase }}
              mountPath: {{ $volumeSpec.mountPath }}
              {{- if $volumeSpec.subPath }}
              subPath: {{ $volumeSpec.subPath }}
              {{- end }}
          {{- end }}
          {{- end }}
          ports:
            - name: "http"
              containerPort: {{ $httpPort }}
            {{- if $spec.service }}
            {{- range $name, $portSpec := $spec.service.extraPorts }}
            - name: {{ $name | kebabcase | quote }}
              containerPort: {{ $portSpec.port }}
            {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $httpPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ $httpPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 10
        {{- range $sidecarName, $sidecarSpec := $spec.sidecars }}
        {{- if $sidecarSpec.enabled }}
        - name: {{ $sidecarName | kebabcase }}
          image: "{{ $sidecarSpec.repo | default $repoBase }}/{{ $sidecarSpec.image }}:{{ $sidecarSpec.tag }}"
          env:
            {{- range $index, $transportName := $spec.useTransports }}
            {{- $transportTarget := "" }}
            {{- if eq (kindOf $transportName) "string" }}
            {{- $transportTarget = $transportName }}
            {{- else }}
            {{- $transportTarget = $transportName.name }}
            {{- end }}
            {{- range $transportKey, $transportValue := index $.Values.transport $transportTarget }}
            - name: {{ $transportKey }}
              {{- if eq (kindOf $transportName) "string" }}
              {{- $transportValue | toYaml | nindent 14 }}
              {{- else }}
              {{- if $transportName.overrides }}
              {{- range $overrideKey, $overrideValue := $transportName.overrides }}
              {{- if eq $overrideKey $transportKey }}
              {{- $overrideValue | toYaml | nindent 14 }}
              {{- end }}
              {{- end }}
              {{- end }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- range $envKey, $envValue := $sidecarSpec.env }}
            - name: {{ $envKey }}
              {{- $envValue | toYaml | nindent 14 }}
            {{- end }}
            - name: PORT
              value: {{ $sidecarSpec.httpPort | default $sidecarHealthPort | quote }}
            - name: OIDC_WELLKNOWN_URL
              value: {{ $wellKnownUrl }}
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_APM_ENABLED
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $sidecarHealthPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 10
        {{- if not $sidecarSpec.httpPort }}
        {{- $sidecarHealthPort = add $sidecarHealthPort 1 }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- if $spec.volumes }}
      volumes:
      {{- range $volumeMountName, $volumeSpec := $spec.volumes }}
        - name: {{ cat $volumeMountName "volume"| kebabcase }}
          {{- if $volumeSpec.secret }}
          secret:
              secretName: {{ $volumeSpec.secret }}
          {{- end }}
          {{- if $volumeSpec.configMap }}
          configMap:
            name: {{ $volumeSpec.name }}
          {{- end }}
      {{- end }}
      {{- end }}
{{- if $spec.service }}
{{- if $spec.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
spec:
  selector:
    app: {{ $serviceName }}
  ports:
    - name: "http"
      protocol: TCP
      port: {{ $httpPort }}
      targetPort: {{ $httpPort }}
    {{- range $name, $portSpec := $spec.service.extraPorts }}
    - name: {{ $name | quote }}
      protocol: {{ $portSpec.type | default "TCP" }}
      port: {{ $portSpec.port }}
      targetPort: {{ $portSpec.port }}
    {{- end }}
{{ end }}
{{ end }}
{{- if $spec.ingress }}
{{- if $spec.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $httpPort }}
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ $tlsSecretName }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}