{{- $serviceName := "secret-request-controller" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $serviceName }}
    app.kubernetes.io/name: {{ $serviceName }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
        app.kubernetes.io/name: {{ $serviceName }}
    spec:
      containers:
        - name: {{ $serviceName }}
          image: {{ $.Values.controllerImage }}:{{ $.Values.controllerTag }}
          env:
            - name: PORT
              value: {{ $.Values.service.port | quote }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.port }}
              protocol: TCP
          resources:
            {{ $.Values.resources | toYaml | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $.Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ $.Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10