apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: secret-request-controller
  namespace: {{ $.Release.Namespace }}
spec:
  generateSelector: true
  parentResource:
    apiVersion: flowcore.io/v1
    resource: secretrequests
  childResources:
    - apiVersion: v1
      resource: secrets
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://{{ $.Release.Name }}.{{ $.Release.Namespace }}:{{ $.Values.service.port }}/sync
    customize:
      webhook:
        url: http://{{ $.Release.Name }}.{{ $.Release.Namespace }}:{{ $.Values.service.port }}/customize