{{- $namespace := .Values.namespace | default .Release.Namespace -}}
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: secret-request-controller
  namespace: {{ $namespace }}
spec:
  generateSelector: true
  parentResource:
    apiVersion: flowcore.io/v1
    resource: secretrequests
  childResources:
    - apiVersion: v1
      resource: secrets
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://{{ .Release.Name }}.{{ $namespace }}:{{ .Values.service.port }}/sync
    customize:
      webhook:
        url: http://{{ .Release.Name }}.{{ $namespace }}:{{ .Values.service.port }}/customize
