{{- $serviceName := "secret-request-controller" -}}
{{- $namespace := $.Values.namespace | default $.Release.Namespace -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ $namespace }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.port }}
  selector:
    app: {{ $serviceName }}
  type: ClusterIP