{{- $tenant := .Values.flowcore.tenant -}}
{{- $repository := .Values.flowcore.configurationRepository -}}
{{- $namespace := printf "org-%s-config" $tenant -}}
{{- $controlPlaneEnv := .Values.flowcore.controlPlaneEnv -}}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-namespace-metadata.label-creator: flowcore
  name: {{ $namespace }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $namespace }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "{{ $controlPlaneEnv }}"
    repoURL: {{ $repository }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true