{{- $microservices := index .Values "flowcore-microservices" "deployments" -}}
{{- $eventSourceActiveDataPump := index $microservices "eventSourceActiveDataPump" -}}
{{- if $eventSourceActiveDataPump.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cold-storage-active-config
data:
  data-sources.json: |
    [
      {
        "tenant": "341309a4-7cb8-4cb1-83f5-35e6ed2e8fdb",
        "dataCore": "ecc024c5-3adf-42a3-aa55-fd3620673192",
        "flowType": "d99ab94e-7548-4bc1-878b-8f5abaa29cb4",
        "eventTypes": [
          "a9e02873-f51f-42d3-8391-17e285bd23d6",
          "6151fd21-e12a-4f42-88b7-ae6a007bc13f",
          "e9b5c630-23e3-493d-a454-15cf19295861"
        ],
        "destination": "http://cold-storage-api:3000/transformers/data-core.1"
      },
      {
        "tenant": "341309a4-7cb8-4cb1-83f5-35e6ed2e8fdb",
        "dataCore": "ecc024c5-3adf-42a3-aa55-fd3620673192",
        "flowType": "b8eb0d1f-325c-48bf-b66b-cc205f8144f7",
        "eventTypes": [
          "cda8ec64-c69a-4039-bf3f-dd81c1f21ffd",
          "1c9ad593-1177-47ee-b208-83b220675b16"
        ],
        "destination": "http://cold-storage-api:3000/transformers/flow-type.1"
      },
      {
        "tenant": "341309a4-7cb8-4cb1-83f5-35e6ed2e8fdb",
        "dataCore": "ecc024c5-3adf-42a3-aa55-fd3620673192",
        "flowType": "2fc4b417-bdcf-4932-8b1e-7e83d3516da9",
        "eventTypes": [
          "29356cfb-0045-4a68-aa4b-1215507b3916",
          "74c1722e-2b0d-4675-a1f5-b49663eb47bd"
        ],
        "concurrency": 1,
        "destination": "http://cold-storage-api:3000/transformers/event-type.1"
      }
    ]
{{- end }}
