apiVersion: v1
kind: ServiceAccount
metadata:
  name: dedicated-configurator-sa
  namespace: flowcore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dedicated-configurator-sa
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dedicated-configurator-sa
subjects:
- kind: ServiceAccount
  name: dedicated-configurator-sa
  namespace: flowcore
roleRef:
  kind: ClusterRole
  name: dedicated-configurator-sa
  apiGroup: rbac.authorization.k8s.io
