apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-source-initdb
  namespace: {{ .Release.Namespace }}
data:
  configure-auth.sh: |
    #!/bin/bash

    # Wait for Cassandra to be ready
    until cqlsh -u cassandra -p "${CASSANDRA_PASSWORD}" -e "describe keyspaces"; do
      echo "Waiting for Cassandra to start..."
      sleep 10
    done

    # Configure system_auth keyspace
    cqlsh -u cassandra -p "${CASSANDRA_PASSWORD}" <<EOF
    ALTER KEYSPACE system_auth 
    WITH REPLICATION = {
        'class': 'NetworkTopologyStrategy',
        'datacenter1': 3
    };

    DESC KEYSPACE system_auth;
    EOF

    # Wait for schema agreement
    echo "Waiting for schema agreement..."
    sleep 30

    # Run repair on all nodes
    nodetool repair -full system_auth

    echo "System_auth keyspace configuration completed"
  initdb.cql: |
    CREATE KEYSPACE flowcore WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'datacenter1' : {{ .Values.flowcore.keyspace.replicationFactor }} };

    CREATE TABLE flowcore.stored_event_stream (
        tenant_id text,
        data_core uuid,
        aggregator text,
        event_type text,
        timebucket text,
        event_id timeuuid,
        serialized_payload text,
        valid_time text,
        metadata map<text, text>,
        PRIMARY KEY ((tenant_id, data_core, aggregator, event_type, timebucket), event_id)
    ) WITH CLUSTERING ORDER BY (event_id ASC)
        AND additional_write_policy = '99p'
        AND bloom_filter_fp_chance = 0.01
        AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
        AND cdc = false
        AND comment = ''
        AND compaction = {'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy', 'compaction_window_size': '24', 'compaction_window_unit': 'HOURS', 'max_threshold': '32', 'min_threshold': '4'}
        AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
        AND memtable = 'default'
        AND crc_check_chance = 1.0
        AND default_time_to_live = 604800
        AND extensions = {}
        AND gc_grace_seconds = 172800
        AND max_index_interval = 2048
        AND memtable_flush_period_in_ms = 0
        AND min_index_interval = 128
        AND read_repair = 'BLOCKING'
        AND speculative_retry = '99p';

    CREATE KEYSPACE flowcore_platform_data WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'datacenter1' : {{ .Values.flowcore.keyspace.replicationFactor }} };

    CREATE TABLE flowcore_platform_data.stored_event_stream (
        tenant_id text,
        data_core uuid,
        aggregator text,
        event_type text,
        timebucket text,
        event_id timeuuid,
        serialized_payload text,
        valid_time text,
        metadata map<text, text>,
        PRIMARY KEY ((tenant_id, data_core, aggregator, event_type, timebucket), event_id)
    ) WITH CLUSTERING ORDER BY (event_id ASC)
        AND additional_write_policy = '99p'
        AND bloom_filter_fp_chance = 0.01
        AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
        AND cdc = false
        AND comment = ''
        AND compaction = {'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy', 'compaction_window_size': '24', 'compaction_window_unit': 'HOURS', 'max_threshold': '32', 'min_threshold': '4'}
        AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
        AND memtable = 'default'
        AND crc_check_chance = 1.0
        AND default_time_to_live = 604800
        AND extensions = {}
        AND gc_grace_seconds = 172800
        AND max_index_interval = 2048
        AND memtable_flush_period_in_ms = 0
        AND min_index_interval = 128
        AND read_repair = 'BLOCKING'
        AND speculative_retry = '99p';

    CREATE KEYSPACE flowcore_archive WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'datacenter1' : {{ .Values.flowcore.keyspace.replicationFactor }} };

    CREATE TABLE flowcore_archive.archive_keys (
        hash_key text PRIMARY KEY
    ) WITH additional_write_policy = '99p'
        AND bloom_filter_fp_chance = 0.01
        AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
        AND cdc = false
        AND comment = ''
        AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
        AND compression = {'chunk_length_in_kb': '16', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
        AND memtable = 'default'
        AND crc_check_chance = 1.0
        AND default_time_to_live = 0
        AND extensions = {}
        AND gc_grace_seconds = 86400
        AND max_index_interval = 2048
        AND memtable_flush_period_in_ms = 0
        AND min_index_interval = 128
        AND read_repair = 'BLOCKING'
        AND speculative_retry = '99p';

    CREATE TABLE flowcore_archive.backup_stream (
        hash_key text,
        event_id timeuuid,
        data text,
        PRIMARY KEY (hash_key, event_id)
    ) WITH CLUSTERING ORDER BY (event_id ASC)
        AND additional_write_policy = '99p'
        AND bloom_filter_fp_chance = 0.01
        AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
        AND cdc = false
        AND comment = ''
        AND compaction = {'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy', 'compaction_window_size': '24', 'compaction_window_unit': 'HOURS', 'max_threshold': '32', 'min_threshold': '4', 'tombstone_threshold': '0.2'}
        AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
        AND memtable = 'default'
        AND crc_check_chance = 1.0
        AND default_time_to_live = 0
        AND extensions = {}
        AND gc_grace_seconds = 43200
        AND max_index_interval = 2048
        AND memtable_flush_period_in_ms = 0
        AND min_index_interval = 128
        AND read_repair = 'BLOCKING'
        AND speculative_retry = '99p';
