apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-source-initdb
  namespace: {{ .Release.Namespace }}
data:
  configure-auth.sh: |
    #!/bin/bash

    # Create a temporary cqlshrc file with credentials
    cat << EOF > ~/.cqlshrc
    [authentication]
    username = cassandra
    password = ${CASSANDRA_PASSWORD}
    EOF

    # Set appropriate permissions
    chmod 600 ~/.cqlshrc

    # Wait for Cassandra to be ready
    until cqlsh -e "describe keyspaces"; do
      echo "Waiting for Cassandra to start..."
      sleep 10
    done

    # Configure system_auth keyspace
    cqlsh <<EOF
    ALTER KEYSPACE system_auth 
    WITH REPLICATION = {
        'class': 'NetworkTopologyStrategy',
        'datacenter1': 3
    };

    DESC KEYSPACE system_auth;
    EOF

    # Wait for schema agreement
    echo "Waiting for schema agreement..."
    sleep 30

    # Run repair on all nodes
    nodetool repair -full system_auth

    # Clean up
    rm -f ~/.cqlshrc

    echo "System_auth keyspace configuration completed"
