apiVersion: v1
kind: ServiceAccount
metadata:
  name: flowcore-kube-log-reader
  namespace: flowcore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flowcore-kube-log-reader
  namespace: org-{{ .Values.flowcore.tenant }}-config
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flowcore-kube-log-reader
  namespace: org-{{ .Values.flowcore.tenant }}-config
subjects:
- kind: ServiceAccount
  name: flowcore-kube-log-reader
  namespace: flowcore
roleRef:
  kind: Role
  name: flowcore-kube-log-reader
  apiGroup: rbac.authorization.k8s.io
