{{- range $sr, $srSpec := $.Values.requests }}
{{ if $srSpec.enabled }}
{{- $destinationNamespace := $.Release.Namespace }}
{{- if $srSpec.destination }}
  {{- if $srSpec.destination.namespace }}
    {{- $destinationNamespace = $srSpec.destination.namespace }}
  {{- end }}
{{- end }}
{{- $destinationName := $srSpec.source.name }}
{{- if $srSpec.destination }}
  {{- if $srSpec.destination.name }}
    {{- $destinationName = $srSpec.destination.name }}
  {{- end }}
{{- end }}
---
apiVersion: flowcore.io/v1
kind: SecretRequest
metadata:
  name: {{ cat $sr $.Release.Namespace | kebabcase }}
spec:
  sourceSecret:
    name: {{ $srSpec.source.name }}
    namespace: {{ $srSpec.source.namespace }}
  destinationSecret:
    name: {{ $destinationName }}
    namespace: {{ $destinationNamespace }}
{{- end }}
{{- end }}