{{- if $.Values.secretStores.enabled }}
{{- range $store, $storeSpec := $.Values.secretStores.stores }}
{{- if $storeSpec.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ cat $store "store" | kebabcase }}
spec:
  provider:
  {{- if eq $storeSpec.type "AWS" }}
    aws:
      service: {{ $storeSpec.storeType }}
      region: {{ $storeSpec.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ $storeSpec.authSecretName }}
            key: access-key
            namespace: {{ $.Release.Namespace }}
          secretAccessKeySecretRef:
            name: {{ $storeSpec.authSecretName }}
            key: secret-access-key
            namespace: {{ $.Release.Namespace }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}