apiVersion: v2
name: flowcore-platform
description: A helm chart for installing a dedicated instance of the Flowcore Platform
type: application
version: 0.0.2
appVersion: 0.0.1
icon: https://avatars.githubusercontent.com/u/114778675?s=200&v=4

dependencies:
  - name: k8ssandra-operator
    version: 1.21.0-20250114171028-a6352fc8
    repository: https://helm.k8ssandra.io
