apiVersion: v2
name: flowcore-platform
description: A helm chart for installing a dedicated instance of the Flowcore Platform
type: application
version: 0.16.2
appVersion: 0.0.1
icon: https://avatars.githubusercontent.com/u/114778675?s=200&v=4

dependencies:
  - name: cassandra
    version: 12.1.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: cassandra.enabled
  - name: valkey
    version: 2.2.3
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: valkey-ha
    condition: valkey-ha.enabled
  - name: valkey
    version: 2.2.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey-single.enabled
    alias: valkey-single
  - name: valkey
    version: 2.2.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey-cache.enabled
    alias: valkey-cache
  - name: nats
    version: 1.2.10
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
  - name: cloudnative-pg
    version: 0.23.0
    repository: https://cloudnative-pg.io/charts/
    condition: postgresql-operator.enabled
  - name: flowcore-microservices
    repository: https://flowcore-io.github.io/flowcore-helm-charts
    version: 2.8.0
    condition: flowcore-microservices.enabled
  - name: kube-arangodb
    repository: https://arangodb.github.io/kube-arangodb
    version: 1.2.26
    condition: arangodb-operator.enabled
