cassandra:
  ## @param cassandra.enabled [default: true] Whether to install the Cassandra instance
  enabled: true
  ## @param cassandra.dbUser [object] The Cassandra user configuration
  dbUser:
    ## @param cassandra.dbUser.existingSecret [default: platform-source-cassandra-user] The name of the existing secret containing the Cassandra user and password
    existingSecret: "platform-source-cassandra-user"
  ## @param cassandra.cluster [object] The Cassandra cluster configuration
  cluster:
    ## @param cassandra.cluster.name [default: platform-source] The name of the Cassandra cluster
    name: platform-source
    ## @param cassandra.cluster.seedCount [default: 2] The number of seed nodes
    seedCount: 2
    ## @param cassandra.cluster.numTokens [default: 16] The number of tokens
    numTokens: 16
    ## @param cassandra.cluster.datacenter [default: datacenter1] The datacenter name
    datacenter: datacenter1
  ## @param cassandra.replicaCount [default: 3] The number of replicas
  replicaCount: 3
  ## @param cassandra.resources [object] The resources for the Cassandra instance
  resources:
    requests:
      ## @param cassandra.resources.requests.cpu [default: 8] The CPU request
      cpu: 8
      ## @param cassandra.resources.requests.memory [default: 16Gi] The memory request
      memory: 16Gi
    limits:
      ## @param cassandra.resources.limits.cpu [default: 8] The CPU limit
      cpu: 8
      ## @param cassandra.resources.limits.memory [default: 16Gi] The memory limit
      memory: 16Gi
  ## @param cassandra.persistence [object] The persistence configuration
  persistence:
    ## @extra cassandra.persistence.storageClass [string] The storage class for the persistent volume
    ## @param cassandra.persistence.size [default: 512Gi] The size of the persistent volume
    size: 512Gi
  ## @param cassandra.metrics [object] The metrics configuration
  metrics:
    ## @param cassandra.metrics.enabled [default: true] Whether to enable the metrics
    enabled: true

